# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ba26ab4a63a06e68e040c899d68d516ef739ba10571064bd4d7f5fb34cee281c13e38254f5a871115cbba57aeb0775b3f4c80d4882920099310b24e13fca4f4

test:
  secret_key_base: 313846b44ff066934891debceab597c5795ec3f7541822ba78b81765b506452926200b6a3cf0fde911ed84c17a8073b2625eccc6f3b7d364557e5295365ad098

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
